services:
    tikishop_api:
        container_name: tikishop_api
        build:
            context: .
            dockerfile: src/Dockerfile.TikiShop.Api
    tikishop_webclient:
        container_name: tikishop_webclient
        build:
            context: .
            dockerfile: src/Dockerfile.TikiShop.WebClient
        ports:
            - 8080:80
    mssql:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: 'Contraseña12345678'
            MSSQL_PID: 'Developer'
        ports:
            - 1433:1433
